/**
 * Catálogo global de espécies. Dado de produto, não de demonstração:
 * sincronizado a cada migração. O tenant pode acrescentar espécies e raças
 * próprias, nunca editar as globais.
 *
 * `observationPanel` define quais sinais vitais a triagem oferece por padrão,
 * porque o painel de um bovino não é o painel de um calopsita.
 */
export interface SpeciesSeed {
  code: string;
  namePt: string;
  nameScientific: string | null;
  taxonClass: 'mammal' | 'bird' | 'reptile' | 'amphibian' | 'fish' | 'other';
  category: 'companion' | 'equine' | 'livestock' | 'wild' | 'exotic';
  defaultWeightUom: 'kg' | 'g' | 'lb';
  supportsGroup: boolean;
  requiresScientificName: boolean;
  observationPanel: string[];
  attributeSchema: Record<string, unknown>;
  sort: number;
  breeds: Array<{ name: string; sizeClass?: 'toy' | 'small' | 'medium' | 'large' | 'giant' }>;
}

const SMALL_PANEL = [
  'weight',
  'temperature',
  'heart_rate',
  'respiratory_rate',
  'mucous_membranes',
  'capillary_refill_time',
  'hydration',
  'body_condition_score',
  'pain_score',
  'mentation',
];

const BIRD_PANEL = ['weight', 'temperature', 'heart_rate', 'respiratory_rate', 'mentation', 'body_condition_score'];

const REPTILE_PANEL = ['weight', 'temperature', 'heart_rate', 'respiratory_rate', 'ambient_temperature', 'mentation'];

const LARGE_PANEL = [
  'weight',
  'temperature',
  'heart_rate',
  'respiratory_rate',
  'mucous_membranes',
  'capillary_refill_time',
  'hydration',
  'body_condition_score',
  'rumen_motility',
];

export const SPECIES_CATALOG: SpeciesSeed[] = [
  {
    code: 'dog',
    namePt: 'Cão',
    nameScientific: 'Canis lupus familiaris',
    taxonClass: 'mammal',
    category: 'companion',
    defaultWeightUom: 'kg',
    supportsGroup: false,
    requiresScientificName: false,
    observationPanel: SMALL_PANEL,
    attributeSchema: {},
    sort: 10,
    breeds: [
      { name: 'Sem raça definida', sizeClass: 'medium' },
      { name: 'Labrador Retriever', sizeClass: 'large' },
      { name: 'Golden Retriever', sizeClass: 'large' },
      { name: 'Pastor Alemão', sizeClass: 'large' },
      { name: 'Bulldog Francês', sizeClass: 'small' },
      { name: 'Shih Tzu', sizeClass: 'toy' },
      { name: 'Poodle', sizeClass: 'small' },
      { name: 'Yorkshire Terrier', sizeClass: 'toy' },
      { name: 'Rottweiler', sizeClass: 'giant' },
      { name: 'Border Collie', sizeClass: 'medium' },
      { name: 'Pinscher', sizeClass: 'toy' },
      { name: 'Dachshund', sizeClass: 'small' },
      { name: 'Beagle', sizeClass: 'medium' },
      { name: 'Pug', sizeClass: 'small' },
      { name: 'Chihuahua', sizeClass: 'toy' },
      { name: 'Husky Siberiano', sizeClass: 'large' },
      { name: 'Boxer', sizeClass: 'large' },
      { name: 'Maltês', sizeClass: 'toy' },
      { name: 'Lhasa Apso', sizeClass: 'small' },
      { name: 'Spitz Alemão', sizeClass: 'small' },
    ],
  },
  {
    code: 'cat',
    namePt: 'Gato',
    nameScientific: 'Felis catus',
    taxonClass: 'mammal',
    category: 'companion',
    defaultWeightUom: 'kg',
    supportsGroup: false,
    requiresScientificName: false,
    observationPanel: SMALL_PANEL,
    attributeSchema: {},
    sort: 20,
    breeds: [
      { name: 'Sem raça definida', sizeClass: 'medium' },
      { name: 'Siamês', sizeClass: 'medium' },
      { name: 'Persa', sizeClass: 'medium' },
      { name: 'Maine Coon', sizeClass: 'large' },
      { name: 'Angorá', sizeClass: 'medium' },
      { name: 'Bengal', sizeClass: 'medium' },
      { name: 'Sphynx', sizeClass: 'medium' },
      { name: 'British Shorthair', sizeClass: 'medium' },
      { name: 'Ragdoll', sizeClass: 'large' },
    ],
  },
  {
    code: 'rabbit',
    namePt: 'Coelho',
    nameScientific: 'Oryctolagus cuniculus',
    taxonClass: 'mammal',
    category: 'exotic',
    defaultWeightUom: 'kg',
    supportsGroup: false,
    requiresScientificName: false,
    observationPanel: SMALL_PANEL,
    attributeSchema: {},
    sort: 30,
    breeds: [
      { name: 'Sem raça definida' },
      { name: 'Mini Lop' },
      { name: 'Angorá' },
      { name: 'Rex' },
      { name: 'Netherland Dwarf' },
    ],
  },
  {
    code: 'rodent',
    namePt: 'Roedor',
    nameScientific: null,
    taxonClass: 'mammal',
    category: 'exotic',
    defaultWeightUom: 'g',
    supportsGroup: false,
    requiresScientificName: true,
    observationPanel: ['weight', 'temperature', 'heart_rate', 'respiratory_rate', 'mentation'],
    attributeSchema: {},
    sort: 40,
    breeds: [
      { name: 'Hamster sírio' },
      { name: 'Hamster anão russo' },
      { name: 'Porquinho-da-índia' },
      { name: 'Chinchila' },
      { name: 'Gerbil' },
      { name: 'Rato twister' },
    ],
  },
  {
    code: 'ferret',
    namePt: 'Furão',
    nameScientific: 'Mustela putorius furo',
    taxonClass: 'mammal',
    category: 'exotic',
    defaultWeightUom: 'kg',
    supportsGroup: false,
    requiresScientificName: false,
    observationPanel: SMALL_PANEL,
    attributeSchema: {},
    sort: 50,
    breeds: [{ name: 'Sem raça definida' }],
  },
  {
    code: 'bird',
    namePt: 'Ave',
    nameScientific: null,
    taxonClass: 'bird',
    category: 'exotic',
    defaultWeightUom: 'g',
    supportsGroup: false,
    requiresScientificName: true,
    observationPanel: BIRD_PANEL,
    attributeSchema: {
      wingSpanCm: { type: 'number', label: 'Envergadura (cm)' },
      ringNumber: { type: 'string', label: 'Número da anilha' },
    },
    sort: 60,
    breeds: [
      { name: 'Calopsita' },
      { name: 'Periquito australiano' },
      { name: 'Papagaio verdadeiro' },
      { name: 'Agapornis' },
      { name: 'Canário belga' },
      { name: 'Arara canindé' },
      { name: 'Cacatua' },
      { name: 'Ring neck' },
    ],
  },
  {
    code: 'reptile',
    namePt: 'Réptil',
    nameScientific: null,
    taxonClass: 'reptile',
    category: 'exotic',
    defaultWeightUom: 'g',
    supportsGroup: false,
    requiresScientificName: true,
    observationPanel: REPTILE_PANEL,
    attributeSchema: {
      terrariumTempC: { type: 'number', label: 'Temperatura do terrário (C)' },
      humidityPercent: { type: 'number', label: 'Umidade (%)' },
      uvbSource: { type: 'string', label: 'Fonte de UVB' },
    },
    sort: 70,
    breeds: [
      { name: 'Jabuti piranga' },
      { name: 'Jabuti tinga' },
      { name: 'Tigre d água' },
      { name: 'Iguana verde' },
      { name: 'Dragão barbudo' },
      { name: 'Gecko leopardo' },
      { name: 'Jiboia' },
      { name: 'Píton real' },
    ],
  },
  {
    code: 'amphibian',
    namePt: 'Anfíbio',
    nameScientific: null,
    taxonClass: 'amphibian',
    category: 'exotic',
    defaultWeightUom: 'g',
    supportsGroup: false,
    requiresScientificName: true,
    observationPanel: ['weight', 'ambient_temperature', 'mentation'],
    attributeSchema: {},
    sort: 80,
    breeds: [{ name: 'Perereca' }, { name: 'Sapo-boi' }, { name: 'Axolote' }],
  },
  {
    code: 'fish',
    namePt: 'Peixe',
    nameScientific: null,
    taxonClass: 'fish',
    category: 'exotic',
    defaultWeightUom: 'g',
    supportsGroup: true,
    requiresScientificName: true,
    observationPanel: ['weight', 'ambient_temperature'],
    attributeSchema: {
      waterTempC: { type: 'number', label: 'Temperatura da água (C)' },
      ph: { type: 'number', label: 'pH' },
      tankLiters: { type: 'number', label: 'Volume do aquário (L)' },
    },
    sort: 90,
    breeds: [{ name: 'Betta' }, { name: 'Carpa koi' }, { name: 'Acará-disco' }, { name: 'Kinguio' }],
  },
  {
    code: 'horse',
    namePt: 'Equino',
    nameScientific: 'Equus caballus',
    taxonClass: 'mammal',
    category: 'equine',
    defaultWeightUom: 'kg',
    supportsGroup: false,
    requiresScientificName: false,
    observationPanel: LARGE_PANEL,
    attributeSchema: {
      heightCm: { type: 'number', label: 'Altura na cernelha (cm)' },
      coat: { type: 'string', label: 'Pelagem' },
      passport: { type: 'string', label: 'Passaporte equino' },
    },
    sort: 100,
    breeds: [
      { name: 'Mangalarga Marchador' },
      { name: 'Quarto de Milha' },
      { name: 'Crioulo' },
      { name: 'Puro Sangue Inglês' },
      { name: 'Campolina' },
      { name: 'Árabe' },
      { name: 'Sem raça definida' },
    ],
  },
  {
    code: 'donkey',
    namePt: 'Asinino',
    nameScientific: 'Equus asinus',
    taxonClass: 'mammal',
    category: 'equine',
    defaultWeightUom: 'kg',
    supportsGroup: false,
    requiresScientificName: false,
    observationPanel: LARGE_PANEL,
    attributeSchema: {},
    sort: 110,
    breeds: [{ name: 'Pêga' }, { name: 'Nordestino' }, { name: 'Sem raça definida' }],
  },
  {
    code: 'cattle',
    namePt: 'Bovino',
    nameScientific: 'Bos taurus',
    taxonClass: 'mammal',
    category: 'livestock',
    defaultWeightUom: 'kg',
    supportsGroup: true,
    requiresScientificName: false,
    observationPanel: LARGE_PANEL,
    attributeSchema: {
      lot: { type: 'string', label: 'Lote' },
      productionStage: { type: 'string', label: 'Fase de produção' },
      milkLitersDay: { type: 'number', label: 'Produção (L/dia)' },
    },
    sort: 120,
    breeds: [
      { name: 'Nelore' },
      { name: 'Girolando' },
      { name: 'Holandesa' },
      { name: 'Gir leiteiro' },
      { name: 'Angus' },
      { name: 'Brahman' },
      { name: 'Jersey' },
      { name: 'Sem raça definida' },
    ],
  },
  {
    code: 'sheep',
    namePt: 'Ovino',
    nameScientific: 'Ovis aries',
    taxonClass: 'mammal',
    category: 'livestock',
    defaultWeightUom: 'kg',
    supportsGroup: true,
    requiresScientificName: false,
    observationPanel: LARGE_PANEL,
    attributeSchema: { lot: { type: 'string', label: 'Lote' } },
    sort: 130,
    breeds: [{ name: 'Santa Inês' }, { name: 'Dorper' }, { name: 'Morada Nova' }, { name: 'Texel' }],
  },
  {
    code: 'goat',
    namePt: 'Caprino',
    nameScientific: 'Capra hircus',
    taxonClass: 'mammal',
    category: 'livestock',
    defaultWeightUom: 'kg',
    supportsGroup: true,
    requiresScientificName: false,
    observationPanel: LARGE_PANEL,
    attributeSchema: { lot: { type: 'string', label: 'Lote' } },
    sort: 140,
    breeds: [{ name: 'Saanen' }, { name: 'Alpina' }, { name: 'Boer' }, { name: 'Anglo-nubiana' }],
  },
  {
    code: 'swine',
    namePt: 'Suíno',
    nameScientific: 'Sus scrofa domesticus',
    taxonClass: 'mammal',
    category: 'livestock',
    defaultWeightUom: 'kg',
    supportsGroup: true,
    requiresScientificName: false,
    observationPanel: LARGE_PANEL,
    attributeSchema: { lot: { type: 'string', label: 'Lote' } },
    sort: 150,
    breeds: [{ name: 'Landrace' }, { name: 'Large White' }, { name: 'Duroc' }, { name: 'Piau' }],
  },
  {
    code: 'poultry',
    namePt: 'Ave de produção',
    nameScientific: 'Gallus gallus domesticus',
    taxonClass: 'bird',
    category: 'livestock',
    defaultWeightUom: 'kg',
    supportsGroup: true,
    requiresScientificName: false,
    observationPanel: BIRD_PANEL,
    attributeSchema: { lot: { type: 'string', label: 'Lote' }, birds: { type: 'number', label: 'Aves no lote' } },
    sort: 160,
    breeds: [{ name: 'Caipira' }, { name: 'Cobb' }, { name: 'Ross' }, { name: 'Isa Brown' }],
  },
  {
    code: 'wild',
    namePt: 'Silvestre',
    nameScientific: null,
    taxonClass: 'other',
    category: 'wild',
    defaultWeightUom: 'g',
    supportsGroup: false,
    requiresScientificName: true,
    observationPanel: ['weight', 'temperature', 'heart_rate', 'respiratory_rate', 'hydration', 'mentation'],
    attributeSchema: {
      ibamaLicense: { type: 'string', label: 'Licença IBAMA' },
      origin: { type: 'string', label: 'Origem (resgate, criadouro, cativeiro)' },
    },
    sort: 170,
    breeds: [],
  },
  {
    code: 'other',
    namePt: 'Outra espécie',
    nameScientific: null,
    taxonClass: 'other',
    category: 'exotic',
    defaultWeightUom: 'g',
    supportsGroup: false,
    requiresScientificName: true,
    observationPanel: ['weight', 'temperature', 'mentation'],
    attributeSchema: {},
    sort: 999,
    breeds: [],
  },
];
